### ISSUE TITLE
[1.16.1] Crash when game is done booting to Main Menu.

### ISSUE THREAD

**Issue by Gbergz** [LeoBeliik/ExtremeSoundMuffler#10]
Title^

**MC:** 1.16.1
**Forge:** 32.0.77
**Mod Version:** 2.0.0-BETA

**Crash-Report:** https://hastebin.com/alacixatuk.pl

**-** Gbergz

**Comment by LeoBeliik** [comment]
is this on a server o single player?

**Comment by Gbergz** [comment]
I can't even enter the game. It crashes as soon forge is done loading then heads to main menu.

**Comment by LeoBeliik** [comment]
I can't reproduce it, so I suppose is a mod incompatibility, mind to share a list of the mods you're using?

**Comment by Gbergz** [comment]
The Crash report mentions the mod Ding, try with that mod installed aswell
and here's the modlist: https://gist.github.com/Gbergz/cdba248227d218f7ae9e51777d4b95aa
