### ISSUE TITLE
Crash from lava sound

### ISSUE THREAD

**Issue by Darkere** [LeoBeliik/ExtremeSoundMuffler#11]
https://pastebin.com/4S2JuTUb

extremeSoundMuffler-2.0.3_Forge-1.16.1.jar
forge-1.16.1-32.0.108

**Comment by LeoBeliik** [comment]
did you have the lava sound muted? if so, was muted with an anchor or with the default method?

**Comment by Darkere** [comment]
Player said he didn't use the mod at all. Although my quick look at the code seemed to suggest otherwise.

**Comment by LeoBeliik** [comment]
can you ask him if the game crashed while world was loading?

**Comment by Darkere** [comment]
![image](https://user-images.githubusercontent.com/4283717/90807340-a087cd80-e31e-11ea-9c83-f88c166ba084.png)
