### ISSUE TITLE
Crash when entering modded dimensions

### ISSUE THREAD

**Issue by Drakoflame** [LeoBeliik/ExtremeSoundMuffler#13]
Problem:
Crashing when entering other mods dimensions (The Midnight and The Abyss)

Steps to reproduce the problem:
Install this mod, Magical Torches, The Midnight/The Abyss, and travel into the dimensions

**Expected behavior:**
Not Crash when entering the dimensions

**Versions:**
  Forge and Extreme sound muffler versions:
Forge: 31.2.37
ESM: 3.0.0
The Abyss: 3.0.1
The Midnight: 0.5.9

**If crashed, please post a link to the crash report:**
 https://cdn.discordapp.com/attachments/743471527827079318/754810110056071258/crash-2020-09-12_20.54.34-client.txt (Midnight crash)
https://cdn.discordapp.com/attachments/743471527827079318/754801738216898600/message.txt (Abyss crash)

**Additional context**
We're on a modded server, but one of our players tried it in single player and they crashed there as well

**Comment by LeoBeliik** [comment]
I can't reproduce this, tho is magic torches who's causing the crash, is totally possible that how I am muffling the sounds is causing the problem, unfortunately magic torches is ARR and I can't know how they are handling this.
Report the crash to them, I'll keep this open just in case.

**Comment by Drakoflame** [comment]
Awesome thank you so much for letting know, I'll be sure to let MT know as well, I submitted more or less the exact same reports to them as well, hopefully they can nail the issue

**Comment by NillerMedDild** [comment]
I'm fairly certain this crash is caused by OptiFine. It even happens when going into the Nether, without having Magic Torches in the instance.

https://github.com/NillerMedDild/Enigmatica6/issues/320
