### ISSUE TITLE
1.16.4 Fabric

### ISSUE THREAD

**Issue by MorningSage** [LeoBeliik/ExtremeSoundMuffler#14]
Hey Leo,

I took a moment to port this mod to Fabric 1.16.4.

https://github.com/MorningSage/ExtremeSoundMuffler-Fabric

It’s not my intention to take credit for your work, but I don’t know how you’d like to have this set up.  Some people like to keep forge and fabric completely separate and others like to have all the code on one repo with different branches.  I can do a PR or leave the code where it is, whichever you’d like.

Just let me know your opinion on the matter and how I can be of assistance.  And thanks for making this mod!

**Comment by LeoBeliik** [comment]
Since I don't know anything about Fabric and you took the time to do it, just keep it and publish it under your regard, just put a link to my version, and send me the link so I add a link to your version too.

Good work! cheers

**Comment by MorningSage** [comment]
Sounds like a plan!

The link (when approved by Curse) is: https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler-fabric

Once it comes up, you'll see a link to the Forge version with credit to you.  The logic is largely the same, so if I get any bug reports that are likely applicable, I'll open a ticket here.
