### ISSUE TITLE
Muffled sounds reset after changing dimensions

### ISSUE THREAD

**Issue by antisocialian** [LeoBeliik/ExtremeSoundMuffler#16]
Using Direwolf20 pack, it currently has "extremeSoundMuffler-3.2_Forge-1.16.4.jar", playing on singleplayer.

Whenever I change dimensions the sounds that were muffled are reset back to no sounds muffled(neither player only nor the anchored sounds are kept).

**Comment by LeoBeliik** [comment]
What version of forge are you using?

**Comment by antisocialian** [comment]
says 1.16.4-forge-35.1.15 on the F3 screen.

**Comment by LeoBeliik** [comment]
it's ok I've already figured out, thanks
