### ISSUE TITLE
client crashes

### ISSUE THREAD

**Issue by Sunekaer** [LeoBeliik/ExtremeSoundMuffler#17]
https://paste.feed-the-beast.com/view/2c021915
forge:35.1.15
extremeSoundMuffler-3.2_Forge-1.16.4.jar

_When clicking the sound muffler button, the client crashes. Apparently only when there's more than one player on the server_

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/55

**Comment by LeoBeliik** [comment]
Does this happens with v3.3?

**Comment by Sunekaer** [comment]
i will check

**Comment by LeoBeliik** [comment]
This should be fixed in v3.4 if it wasn't already fixed in v3.3, fell free to comment if this is not the case and I'll re-open this issue.
