### ISSUE TITLE
Null on dim change

### ISSUE THREAD

**Issue by Sunekaer** [LeoBeliik/ExtremeSoundMuffler#18]
https://paste.sunekaer.com/uhupixupun.rb

extremeSoundMuffler-3.3_Forge-1.16.4.jar
forge: 35.1.28

**Comment by LeoBeliik** [comment]
Can you reproduce this bug easily?

**Comment by Sunekaer** [comment]
Let me check later, the issue happened when I was changing dims fast

**Comment by Sunekaer** [comment]
I wasnt able to get it to do it again this time

**Comment by LeoBeliik** [comment]
Yeah, i couldn't reproduce it either, i suppose it needs specifically conditions to trigger, thanks for testing it.
