### ISSUE TITLE
Change Icons to Left or highlight rows

### ISSUE THREAD

**Issue by cobbkris** [LeoBeliik/ExtremeSoundMuffler#19]
**Is your feature request related to a problem? Please describe.**
For small GUI (or bad eyes), it is hard to see what icons line up with the corresponding sounds.

**Describe the solution you'd like**
Change the mute/play icons to the left side, or highlight every other row so you can click on the correct button.

**Describe alternatives you've considered**
n/a

**Additional context**
Great mod!!

**Comment by LeoBeliik** [comment]
could you give me some feedback? c:
![imagen](https://user-images.githubusercontent.com/11804768/104129806-9d808e80-534c-11eb-9af4-6f2cd3b20e22.png)

**Comment by cobbkris** [comment]
Perfect!
