### ISSUE TITLE
Anchors data not loaded

### ISSUE THREAD

**Issue by jerry1333** [LeoBeliik/ExtremeSoundMuffler#22]
**Versions**
Indicate the versions for:
- extremeSoundMuffler-3.7_Forge-1.16.5.jar
- Forge 1.16.5-forge-36.0.14
- Additional mod(s): Direwolf20 pack v1.6.1 https://www.feed-the-beast.com/modpack/ftb_presents_direwolf20_1_16

**Describe the bug**
Anchors data is not shown when rejoining server.

**To Reproduce**

1. Join server
2. Set anchor and muffle some sounds
3. Leave server and join again
4. Check anchors

**Expected behavior**
Show anchors data.

**Screenshots or Crashlog**
![2021-02-25_22 11 44](https://user-images.githubusercontent.com/984193/109218825-319c9d00-77b7-11eb-8a13-c8958ad10c27.png)
After rejoin:
![2021-02-25_22 12 49](https://user-images.githubusercontent.com/984193/109218960-5bee5a80-77b7-11eb-82e1-e9d372ebb255.png)

**Additional context**
Also providing ESM directory - for me it looks like Anchors.dat is broken and that's why it gets lost.
[ESM.zip](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/6045808/ESM.zip)

**Comment by ProsperCraft** [comment]
This is a report stating that each time you load the pack everything you had muffled has to be reset correct?

**Comment by LeoBeliik** [comment]
> 
> 
> This is a report stating that each time you load the pack everything you had muffled has to be reset correct?

it was, yes, and it was fixed in v3.8
