### ISSUE TITLE
ability to silence named entities

### ISSUE THREAD

**Issue by BKSDTeam** [LeoBeliik/ExtremeSoundMuffler#23]
**Is your feature request related to a problem? Please describe.**
What frustrates me with recording for instance in my villager trading hall is that a zombird is alway moaning in the background.
Yes i can mute the zombird with your mod,  but then all zombirds are muted.

**Describe the solution you'd like**
What would solve this issue for me is having the ability to mute named entities like "Silence Me" datapack.
But then clientside, cause not all vanilla servers have that datapack installed. having a way to do that clientside would solve this problem.

**Describe alternatives you've considered**
I have no alternative you are my last hope.

**Additional context**
Maybe adding a category to switch between the recent, muffled, all and "Named"
would be an option?

**Comment by BKSDTeam** [comment]
On a side note, I love your mod, and recommend it to everyone. I use it all the time.
Thanks for putting your time and effort in it for us to enjoy.

**Comment by LeoBeliik** [comment]
Unfortunately the event that gets the sounds doesn't distinguish what makes the sound, just what sound is, this is why you can't block a sugarcane break sound without also blocking the grass break sound is a limitation I tried to overcome in the past but I was unsuccessfully.

Now if I'm understood your problem correctly, couldn't you use an Anchor to mute the sound only in that area?
