### ISSUE TITLE
Anchors not persisting between game restarts.

### ISSUE THREAD

**Issue by ghastlybespoke04** [LeoBeliik/ExtremeSoundMuffler#24]
**Versions**
- extremeSoundMuffler-3.9_Forge-1.16.5
- forge-1.16.5-36.1.4
- Additional mod(s) - None

**Bug Description**\
Anchors from previous sessions are not being loaded when trying to play the game. After further inspection it would seem that no data is being saved into the "*ESM\soundsMuffled.dat*". The only content inside the "*soundsMuffled.dat*" is `{}` (a pair of empty brackets). The "Date Modified" meta data of the *soundsMuffled.dat* file is updated every time I start the game so it would seem that empty data is being written to it.

**To Reproduce**
1. Start Minecraft.
2. Load current world being played.
3. Set anchors at animal farms.
4. Save game and exit.
5. Start Minecraft and load current world.
6. Check anchors.

**Expected behavior**\
Anchors should load from previous gaming session but do not.

**Screenshots or Crashlog**\
N/A

**Additional context**\
Providing ESM directory for trouble shooting.
[ESM.zip](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/6349909/ESM.zip)

**Comment by LeoBeliik** [comment]
Are you playing on a server or just sp?

**Comment by ghastlybespoke04** [comment]
I am playing single player. I have updated forge to *forge-1.16.5-36.1.6* and this bug disappeared. It seems that a bug in *forge-1.16.5-36.1.4* causes ESM to not save or load the anchors.

This bug has been solved and can be closed.
Thank you.
