### ISSUE TITLE
Minecart sounds are not mufflable

### ISSUE THREAD

**Issue by henkelmax** [LeoBeliik/ExtremeSoundMuffler#25]
**Versions**
Indicate the versions for:
- Extreme sound muffler 3.9 and 3.10
- Forge 36.1.0

**Describe the bug**
Minecart sounds are not mufflable.

**To Reproduce**
1. Open the sound muffler GUI
2. Change the volume of `entity.minecart.riding:minecraft` and `entity.minecart.inside:minecraft` to something like 90%
3. No minecart sound plays at all

**Expected behavior**
The sound to be playing with 90% volume

**Screenshots or Crashlog**
![image](https://user-images.githubusercontent.com/13237524/118010040-eeca7a00-b34e-11eb-9108-5cc418f3544e.png)

**Additional context**
I think the problem is because these sounds are `TickableSound` sounds.

Another problem is muffling the sound of cars from the [Ultimate Car Mod](https://github.com/henkelmax/ultimate-car-mod) or planes of the [Ultimate Plane Mod](https://github.com/henkelmax/ultimate-plane-mod).
When reducing the volume of these sounds, it causes the sound to be stacked infinitely.

https://user-images.githubusercontent.com/13237524/118011169-01917e80-b350-11eb-911a-eb570438a695.mp4

**Comment by LeoBeliik** [comment]
Yes I am aware of this problem but I dunno how to fix it. My hopes are that I'll find a solution with mixins but I haven't had time to implement that yet :c

**Comment by henkelmax** [comment]
> Yes I am aware of this problem but I dunno how to fix it. My hopes are that I'll find a solution with mixins but I haven't had time to implement that yet :c

I created a PR that fixes the tickable sound issues with mixins. If you have any questions about it, let me know :)
