### ISSUE TITLE
[1.16.5-Forge] Mark mod as client side only, makes server "fml server incompatible" in server list.

### ISSUE THREAD

**Issue by Gbergz** [LeoBeliik/ExtremeSoundMuffler#27]
**Versions**
- Extreme sound muffler: 3.11_Forge-1.16.5
- Forge: 36.1.18
- Additional mod(s) No mods.

**Describe the bug**
If mod is missing on server it makes the server ping "Incompatible FML Modded Server".

**To Reproduce**
1. Install mod on client.
2. Don't install on server.
3. Add server to multiplayer list.
4. Ping it.
5. "Incompatible FML Modded Server".
![image](https://user-images.githubusercontent.com/26634554/119142325-a8f46c80-ba46-11eb-947f-4f96413ce50c.png)

**Expected behavior**
That the modlist is compatible. showing a green checkmark like below:
![image](https://user-images.githubusercontent.com/26634554/119153248-5ec4b880-ba51-11eb-9e2d-7918e8d27fda.png)

**Additional context**
If possible, mark mod as client only.

**Comment by Gbergz** [comment]
This is an issue again in the latest release from 2 days ago.
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler/files/3345051

**Comment by LeoBeliik** [comment]
It's marked as clientside if they clientside option in the config is set to true.

**Comment by Gbergz** [comment]
Ah, guess that is new and I missed it noted in a changelog.
