### ISSUE TITLE
Dynamic surroundings mod compat issue

### ISSUE THREAD

**Issue by darknesschaos** [LeoBeliik/ExtremeSoundMuffler#28]
**Versions**
Indicate the versions for:
- Extreme sound muffler 1.16.4-4.0.4.2
- Forge 36.1.32
- Additional mod(s) (If bug is due incompatibility)
Dynamic Surroundings
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings

**Describe the bug**
When using Dynamic Surroundings and ESM together, the ESM can no longer mute or detect sounds.

**To Reproduce**
Use ESM. Tested with chicken and cows

**Expected behavior**
Should mute sounds as expected.

**Screenshots or Crashlog**
If applicable, add screenshots or a crashlog to help explain your problem.

**Additional context**
N/A

**Comment by LeoBeliik** [comment]
what version of ESM are you using? 1.16.4-4.0.4.2 is not a version of this mod

**Comment by darknesschaos** [comment]
Sorry, I grabbed the version from Dynamic Surroundings, ESM's is 3.13-1.16.5, which should be the latest available.

**Comment by LeoBeliik** [comment]
Apparently DS has their own muffler system (check your keybinds), so use that instead. 👍🏻
