### ISSUE TITLE
Compatibility with Inventorio

### ISSUE THREAD

**Issue by xrosbeast** [LeoBeliik/ExtremeSoundMuffler#29]
With [Inventorio](https://github.com/Lizard-Of-Oz/Inventorio) installed as well as this mod, the button appears underneath the tool belt slots, which makes it difficult to use.

[Here is a photo:](https://camo.githubusercontent.com/a166c751121c8620c5fd8e12bdd45ef9e4a6cfc521bcc9dd781c7e2b839fa3be/68747470733a2f2f692e696d6775722e636f6d2f613464625644682e706e67)

I [contacted](https://github.com/Lizard-Of-Oz/Inventorio/issues/44) the Inventorio dev to ask if he could fix it and after trying it, this is what he said. 

"Unfortunately, this request had to be rejected.
Trying to fix it "on my end" has ended up being very janky and require injects into those two mods, which can break at any time they update.
I'd recommend asking the mod authors to do something "on their end" if possible."

Is there any possible fix for this issue?

**Comment by LeoBeliik** [comment]
I'll probably add a way to move the button around someday, but for now you can disable it in the configs and use a hotkey to open the GUI.

**Comment by xrosbeast** [comment]
Alright, that could work. I'll just have to convey to players that the mod is there and they can bind it to a key.
