### ISSUE TITLE
ESM doesn't seem to muffle any machines anymore..

### ISSUE THREAD

**Issue by SgtMorrigahnGaming** [LeoBeliik/ExtremeSoundMuffler#30]
**Versions**
Indicate the versions for:
- Extreme sound muffler extremeSoundMuffler-3.13-1.16.5.jar
- Forge 36.2.2
- Additional mod(s) (If bug is due incompatibility)
AkashicTome-1.4-16
Apotheosis-1.16.4-4.6.1
appleskin-forge-mc1.16.x-2.1.0
architectury-1.20.29-forge
AutoRegLib-1.6-49
BetterCaves-Forge-1.16.4-1.1.2
BetterMineshafts-Forge-1.16.4-2.0.4
BiomesOPlenty-1.16.5-13.1.0.477-universal
Bookshelf-Forge-1.16.5-10.2.27
BotanyPots-1.16.5-7.0.17
buildinggadgets-1.16.5-3.8.0
caelus-forge-1.16.5-2.1.3.1
cloth-config-4.11.26-forge
CodeChickenLib-1.16.5-4.0.2.429-universal
cofh_core-1.16.5-1.3.1
comforts-forge-1.16.5-4.0.1.2
Controlling-7.0.0.23
CookingForBlockheads_1.16.5-9.3.3
CraftingTweaks_1.16.5-12.2.1
CraftTweaker-1.16.5-7.1.0.374
Cucumber-1.16.4-4.1.10
curios-forge-1.16.5-4.0.5.2
curiouselytra-forge-1.16.5-4.0.2.3
curiousjetpacks-1.4c-1.16.5
Cyclic-1.16.5-1.3.5
dankstorage-3.16
DarkUtilities-1.16.5-8.0.10
DefaultOptions_1.16.5-12.2.1
DungeonCrawl-1.16.5-2.3.2
DynamicSurroundings-1.16.4-4.0.4.2
elevatorid-1.16.5-1.7.13
EnderStorage-1.16.5-2.8.0.168-universal
extradisks-1.16.4-1.5.1
ExtraStorage-1.16.5-1.4.1
ExtremeReactors2-1.16.4-2.0.23
FastFurnace-1.16.4-4.4.0
FastLeafDecay-v25
FastWorkbench-1.16.4-4.5.1
flatbedrock-1.16.4-1.1.6
FluxNetworks-1.16.5-6.1.7.12
ftb-chunks-forge-1605.3.1-build.41
ftb-essentials-1605.1.4-build.13
ftb-library-forge-1605.3.1-build.58
ftb-teams-forge-1605.2.1-build.20
ftb-ultimine-forge-1605.3.0-build.25
globalxp-1.16.5-v1.8
industrial-foregoing-1.16.5-3.2.14.4-11
IronJetpacks-1.16.5-4.2.1
JAOPCA-1.16.5-3.4.0.12
jei-1.16.5-7.7.1.118
jeiintegration_1.16.5-7.0.1.15
JEITweaker-1.16.5-1.0.1.34
journeymap-1.16.5-5.7.3
JustEnoughResources-1.16.5-0.12.1.127
light-overlay-5.8.1
Mantle-1.16.5-1.6.115
mcjtylib-1.16-5.0.22
Mekanism-1.16.5-10.0.21.448
MekanismAdditions-1.16.5-10.0.21.448
MekanismGenerators-1.16.5-10.0.21.448
MekanismTools-1.16.5-10.0.21.448
metalbarrels-1.16.2-3.3b
mining_dimension-1.16.5-1.0.5
modnametooltip_1.16.2-1.15.0
MouseTweaks-2.14-mc1.16.2
MouseTweaks-2.14-mc1.16.2
mysticalworld-1.16.5-0.3.2.17
NetherPortalFix_1.16.3-7.2.1
PackingTape-1.16.5-0.10.1
Patchouli-1.16.4-53.1
pedestals-0.8s_hotfix_5
Placebo-1.16.4-4.5.0
rangedpumps-0.8.2
refinedstorage-1.9.15
refinedstorageaddons-0.7.3
ResourcefulBees-1.16.5-0.6.7.2b
rftoolsbase-1.16-2.0.11
rftoolsbuilder-1.16-3.1.1
rftoolspower-1.16-3.0.9
rftoolsutility-1.16-3.1.1
Runelic-1.16.5-7.0.1
simplefarming-1.16.5-1.3.8
simplybackpacks-1.16.3-1.4.13
SoL-Carrot-1.16.5-1.10.0
StorageDrawers-1.16.3-8.3.0
swingthroughgrass-1.16.4-1.5.3
TConstruct-1.16.5-3.1.1.252
theoneprobe-1.16-3.1.4
thermal_dyenamics-1.16.4-1.0.0
thermal_expansion-1.16.5-1.3.0
thermal_foundation-1.16.5-1.3.2
thermal_innovation-1.16.5-1.3.0
Tiny-Coal-1.16.4-1.0.0
titanium-1.16.5-3.2.8.4-10
Toast-Control-1.16.4-4.3.1
tombstone-1.16-6.4.7
torchmaster-2.3.7
TrashSlot_1.16.3-12.2.1
valhelsia_core-16.0.9
valhelsia_structures-1.16.5-0.1.4
Waystones_1.16.5-7.6.2
YungsApi-1.16.4-Forge-12
ZeroCore2-1.16.4-2.0.21

**Describe the bug**

ESM won't muffle any sound from Mekanism, Thermal or Industrial Foregoing mods ( as far as I have tested )
Tried with and without an anchor
It can't rescan for sounds
The button for altering between the three systems ( show all, recent, muffled ) only gives access to "show all" and "recent" I have to exit out of the window and open it again ( I have added a hotkey for ESM )
From my understanding ESM won't muffle sounds from entities, waterfalls and such due to Dynamic Surround mod is installed so I have not counted them in this.

**To Reproduce**
1. Create a new world
2. Play until you can build/craft any of the mekanism, thermal or Industrial Foregoing machines, or place them in creative
3. Try to muffle them

**Expected behavior**
Expect the sounds chosen to be muffled.

**Screenshots or Crashlog**
If applicable, add screenshots or a crashlog to help explain your problem.

**Additional context**

Been trying to uninstall, remove all config files ( for ESM ), restarted Minecraft, stopped, reinstalled ESM, but nothing worked.
I honestly don't know if any of the other mods are conflicting, but I can't find a logical mod that would interfere with ESM.
If there's something I've overlooked that would fix this, I am sorry

Best regards
Arild Nagel-Dahl

**Comment by LeoBeliik** [comment]
ESM doesn't work if Dynamic Surroundings is installed due to how DS changes the mixins. Also DS has their own sound muffler
