### ISSUE TITLE
Black particles when breaking blocks and killing mobs

### ISSUE THREAD

**Issue by EmanuelLopesS2** [LeoBeliik/ExtremeSoundMuffler#31]
### Extreme sound muffler version

3.19

### Forge version

1.18.1 - 39.0.5

### Additional mod(s) version (If bug is due incompatibility)

All mods I have installed(I tested removing one by one and only muffler does this):

OptiFine_1.18.1_HD_U_H4
MouseTweaks-forge-mc1.18-2.18
jei-1.18.1-9.1.0.46
JustEnoughResources-1.18.1-0.13.1.137
journeymap-1.18-5.8.0alpha9
InventoryHud_[1.18].forge-3.4.4
GameMenuModOption-1.18-Forge-1.13
fullbrightnesstoggle_1.18.1-1.4
forge-1.18.1-39.0.5-installer
extremeSoundMuffler-3.19_1.18
collective-1.18.1-3.8
cloth-config-6.1.48-forge
BetterF3-1.2.2-Forge-1.18

### Describe the bug

When mining for example

![unknown](https://user-images.githubusercontent.com/38889284/146855750-90d26ba2-6266-4e9a-a4b8-c4b4112f6897.png)

### Steps to reproduce

Simply install the mod and kill mobs or mine some blocks, don't need to have any sound muffled

**Comment by LeoBeliik** [comment]
This is actually a [Forge bug](https://github.com/MinecraftForge/MinecraftForge/issues/8221), I don't know why you only experience it with ESM, but unfortunately I don't think I can do anything about it.

**Comment by EmanuelLopesS2** [comment]
ho thanks for the explanation, but the weird thing is that only happens with forge, btw I have a friend who has Fabric and he doesn't have this bug.
Anyways thanks again
