### ISSUE TITLE
🐞 Mixin issue

### ISSUE THREAD

**Issue by NightOps007** [LeoBeliik/ExtremeSoundMuffler#32]
### Extreme sound muffler version

3.17

### Forge version

1.16.5 - 36.2.21

### Additional mod(s) version (If bug is due incompatibility)

See log file.

### Describe the bug

mixin issue?

### Steps to reproduce

Crashes while starting minecraft.

[crash-2022-01-05_15.48.53-client.txt](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/7818466/crash-2022-01-05_15.48.53-client.txt)

### Additional context

Error didn't occur when I was using forge 36.2.0. I had tried to update the version to 36.2.21 to support requirements of another mod I had wanted to install. That's when the issue started to appear, hadn't even installed the new mod yet, just updated forge. Although the forge team may fix this by the next recommended release, it could also be evidence that the next recommended release may be incompatible with this mod. Might be worth looking into ahead of time.

**Comment by LeoBeliik** [comment]
hmm, I can't reproduce this, could you try deleting the config/extremesoundmuffler-client.toml files and starting your game again?

**Comment by LeoBeliik** [comment]
Did anything changed?

**Comment by RebelliousUno** [comment]
This looks like the same crashlog as #35 so it'd be good to see if OP has the same issue of multiple versions of the mod in the mods folder
