### ISSUE TITLE
🐞 

### ISSUE THREAD

**Issue by RebelliousUno** [LeoBeliik/ExtremeSoundMuffler#35]
### Extreme sound muffler version

3.20

### Forge / Fabric version

39.0.10

### Describe the bug

NPE on start up after updating to 3.20 in modpack

Guessing there's a missing config item 

### Crashlog
*in comment*

**Comment by RebelliousUno** [comment]
[crash-2022-01-10_20.24.35-client.txt](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/7841735/crash-2022-01-10_20.24.35-client.txt)

**Comment by RebelliousUno** [comment]
```
#general settings
[general]
	#Blacklisted Sounds - add the name of the sounds to blacklist, separated with comma
	forbiddenSounds = ["ui.", "music.", "ambient."]
	#Allow the "ALL" sounds list to include the blacklisted sounds?
	lawfulAllList = false
	#Volume set when pressed the mute button by default
	#Range: 0.0 ~ 0.9
	defaultMuteVolume = 0.0
	#Set to true to move the muffle and play buttons to the left side of the GUI
	leftButtons = false
	#Show tips in the Muffler screen?
	showTip = true
	#Whether or not use the dark theme
	useDarkTheme = false

#Inventory button settings
[inventory_button]
	#Disable the Muffle button in the player inventory?
	disableInventoryButton = false
	#Coordinates for the Muffler button in the player inventory.
	# You can change this in game by holding the RMB over the button and draging it around
	#Range: > -2147483648
	invButtonX = 75
	#Coordinates for the Muffler button in the player inventory. 
	#You can change this in game by holding the RMB over the button and draging it around
	#Range: > -2147483648
	invButtonY = 7

#Anchor settings
[Anchors]
	#Disable the Anchors?
	disableAnchors = false

```
Is the config

**Comment by RebelliousUno** [comment]
(also crashes in a version without optifine and with latest version of forge)

**Comment by LeoBeliik** [comment]
can you send the latest.log please?

**Comment by RebelliousUno** [comment]
[latest.log](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/7842118/latest.log)
Sure thing here you go

**Comment by LeoBeliik** [comment]
I can't repro this on my end, and I have no clue what could be causing this, but.. try deleting the config file and downloading the mod again maybe?

**Comment by RebelliousUno** [comment]
So, rolled back to 3.19, all fine, 
roll forward to 3.20 falls over
update to 3.21 with existing config - Crashes (though maybe it also had 3.20 in at the same time? Curseforge is being weird?)
3.21 deleting the config - recreates the config
```

#General settings
[general]
	#Blacklisted Sounds - add the name of the sounds to blacklist, separated with comma
	forbiddenSounds = ["ui.", "music.", "ambient."]
	#Allow the "ALL" sounds list to include the blacklisted sounds?
	lawfulAllList = false
	#Volume set when pressed the mute button by default
	#Range: 0.0 ~ 0.9
	defaultMuteVolume = 0.0
	#Set to true to move the muffle and play buttons to the left side of the GUI
	leftButtons = false
	#Show tips in the Muffler screen?
	showTip = true
	#Whether or not use the dark theme
	useDarkTheme = false

#Inventory button settings
[inventory_button]
	#Disable the Muffle button in the player inventory?
	disableInventoryButton = false
	#Coordinates for the Muffler button in the player inventory.
	# You can change this in game by holding the RMB over the button and draging it around
	#Range: > -2147483648
	invButtonX = 75
	#Coordinates for the Muffler button in the player inventory. 
	#You can change this in game by holding the RMB over the button and draging it around
	#Range: > -2147483648
	invButtonY = 7

#Anchor settings
[Anchors]
	#Disable the Anchors?
	disableAnchors = false
```

**Comment by RebelliousUno** [comment]
OK, 
So I think I know what's going on now with a bit more testing
Seems like After updating the profile in Curseforge, it's leaving the old version of the mod (3.19) hanging around
But when 3.19 and 3.20/3.21 are in the mods folder together, they don't get along and things pop.

Just had a fresh version of this profile, updated 3.19-3.21 (Crashed) remove 3.19 from mods folder all fine...
🤷‍♂️

**Comment by LeoBeliik** [comment]
So is curseforge not updating the mod but just adding a new instance of it? it sure won't work if 2 versions are installed but cf should not do that.

**Comment by RebelliousUno** [comment]
Seems that way, it seems to have done it with a few other mods as well...weird.
Happy that it's working with 3.21 on its own anyways
Happy to close the issue with a Known Error in case it shows up again (ie make sure it's the only version in the mod folder)

**Comment by LeoBeliik** [comment]
I'll add a warning in 3.22 about this, thank you for your help 👍🏻

**Comment by RebelliousUno** [comment]
Nws, thanks for your hard work :) appreciate the mod
