### ISSUE TITLE
1.17.1 Fabric Port please!

### ISSUE THREAD

**Issue by MSandro** [LeoBeliik/ExtremeSoundMuffler#36]
Hello, I really like this mod, but I would be verry happy, if you could port it back to 1.17.1 Fabric.
There is no working Sound Muffler Mod for this version as I know.

Thanks a lot. 11.71

**Comment by LeoBeliik** [comment]
And here I though the point of Fabric was to be always in the latest version, smh 😁 
But yeah, I'll do it, in fact, it's already uploaded on CF.
Thank you very much ❤️

**Comment by MSandro** [comment]
Thank you very much. Sure but many mods are still not ported to 1.18.1 so I am still working on my 1.17.1 Skyblock Modpack.
