### ISSUE TITLE
🐞  Issue with null pointer exception on boot

### ISSUE THREAD

**Issue by Succulentbow** [LeoBeliik/ExtremeSoundMuffler#37]
### Extreme sound muffler version

3.23

### Forge / Fabric version

39.0.59

### Describe the bug

On boot it says there is a null pointer exception and that it's because 

### Steps to reproduce

I've got nothing, I just updated everything to the newest version and your mod doesn't work correctly after I updated the others.

### Crashlog

https://pastebin.com/LRHB2Kfh

### Additional context

lots of other mods, slightly modified Enigmatica 8. I tried every version currently released and the problem stayed, and I couldn't remove the mod either.

**Comment by LeoBeliik** [comment]
Are you using the curseforge laucher? look in your mods folder if you have more than one version of the mod.
if not send the latest.log

**Comment by Succulentbow** [comment]
> Are you using the curseforge laucher? look in your mods folder if you have more than one version of the mod. if not send the latest.log

I am using the curseforge launcher. There were 3 versions in the mods folder and when I removed the extras the null pointer exception seemed to be fixed, thanks.

**Comment by LeoBeliik** [comment]
no problem. I think they fixed that recently so I'll suggest you to update the cf app.
