### ISSUE TITLE
extreme sound muffler config issue🐞 

### ISSUE THREAD

**Issue by Polarite** [LeoBeliik/ExtremeSoundMuffler#39]
### Extreme sound muffler version

3.22

### Forge / Fabric version

fabric

### Describe the bug

when opening the mod after first time, it gives an error about creating a file that already exists.

### Crashlog

https://paste.ee/p/N4Jb2

### Additional context

https://paste.ee/p/p2LlP

Latest log for mod list and everything

**Comment by LeoBeliik** [comment]
does it crash or just complains?
