### ISSUE TITLE
Item based sound mufflers

### ISSUE THREAD

**Issue by Renari** [LeoBeliik/ExtremeSoundMuffler#42]
**Describe the solution you'd like**
A block that would open the extreme sound muffler ui and block sounds around it for all players.

**Additional context**
If added it would also be nice to have an option to disable the in-inventory muffler.

**Comment by LeoBeliik** [comment]
Tried to do it a few times, never liked how it works, this also would remove the clientside only feature of the mod, which I don't like.
So in short, this is out of the scope of the mod.
You can disable the inventory button already and set a keybind to open the GUI.
