### ISSUE TITLE
Would be nice if the recent list, ordered the list as to the most recently heard sound 

### ISSUE THREAD

**Issue by JustJinxed** [LeoBeliik/ExtremeSoundMuffler#43]
**Is your feature request related to a problem? Please describe.**
I'm trying to track down the sound that is made when Create (the mod) fells a tree using its Mechanical Saw. I've marked everything in the recent section to no effect. 

**Describe the solution you'd like**
It'd be really neat if the muffler UI had an area at the bottom of about three text lines that scrolled the name of the sounds, kind of like how the subtitles settings does, but with the actual name of the sound being played at the time it happens. And if the recent box was ordered by the most recently played sound

**Describe alternatives you've considered**
I've tried turning on subtitles to track this sound down, but all it says is "block break". I've marked off all sounds with "break" in their name, to no avail. Not sure what sound Create is playing when it fells trees. It sounds like a REALLY loud crop break

**Additional context**
I'm brainstorming more than anything. Clearing the recent and letting it play, there's four distinct sounds listed. None of which hit on this particular nuisance. It's as if the sound is invisible to the muffler mod, or something is overriding?
 
![example](https://user-images.githubusercontent.com/1085641/176656371-f304db13-5236-4f6d-ba0b-1c77d8ba82ff.png)

**Comment by LeoBeliik** [comment]
What version of ESM are you using? That should definitely be muffling the tree breaking noises so it might be a problem on my end.
And yeah, I'm gonna make the recent sound list have a better logic on how it shows the newer sounds

**Comment by JustJinxed** [comment]
It's extremesoundmuffler-3.27_forge-1.18.x.jar with create-mc1.18.2_v0.4.1.jar
(Nestled in the Direwolf20 modpack ver 1.6.1, with a couple of other additions)
It COULD be a malfunctioning mod interaction, but I kind of doubt it- there's no environmental or other sound mixin mods that I'm aware of. But here's a modlist of what I'm running jic: https://pastebin.com/UrSWxkYK

**Comment by LeoBeliik** [comment]
I tested it with the dw20 pack v1.6.1 and it does muffle the sounds correctly, are you sure the Anchor location is correct?

**Comment by JustJinxed** [comment]
... So I tried from a fresh client start, and .. swear my config must be in some sort of limbo. Here's the UI / but get this.. it's muting just fine!
![What in the](https://user-images.githubusercontent.com/1085641/176801229-8329171a-63c2-44c7-97e1-7451679198fc.png)

Deleted the 3rd slot and started over, blocking grass.break and wood.break -- this worked as expected UI and Muffle working properly. 
Restarted the client, and everything still working, no problems. Reset the client again just in case, and it's still working. 
I'm very sure I had the right anchor location set, as the coords are near identical in both screen shots.
Quirk, subatomic particle interference? I have no idea, but I'm really sorry for the ghost hunt. 
If it comes back and I can reliably recreate it, I'll let you know.

**Comment by LeoBeliik** [comment]
The logic for the list to be ordered gets messy with the current way that the mod works and clearing the recent sound list kinda already fixes this, so for the moment I won't change it, maybe in the future.
