### ISSUE TITLE
Anchors are erased on dimension change and game restart🐞 

### ISSUE THREAD

**Issue by PORTB** [LeoBeliik/ExtremeSoundMuffler#44]
### Extreme sound muffler version

3.2.7_forge-1.18.1

### Forge / Fabric version

40.1.60

### Describe the bug

Anchors don't persist from dimension changes or world reloads

### Steps to reproduce

1. Click on a number in the top bar
2. Select some sounds to muffle
3. Click set anchor button
4. Change dimension or restart
5. Anchor is gone
6. My ears suffer

**Comment by LeoBeliik** [comment]
I can't reproduce it, does the Anchors work correctly until you log out or change dimensions?
Are you playing on a server?
Can you share a list of the mods you're using?

**Comment by PORTB** [comment]
I figured out it was happening because my world name contains a character (':') that windows doesn't like in directories:
```
[Render thread/ERROR] ESM: Error saving the Anchor listjava.io.FileNotFoundException: ESM\NullPointerException: null\anchors.dat (The filename, directory name, or volume label syntax is incorrect)
```
so the issue is that it was not saving with world names containing invalid path characters

**Comment by ghost** [comment]
I don't have invalid chars in my world name and I have a similar issue by which it looks for an anchors file that doesn't exist (because I've never made any anchors):

```
[16:19:36] [Render thread/ERROR]: ESM: Error loading Anchor list
java.io.FileNotFoundException: ESM\Deez 26\anchors.dat (The system cannot find the path specified)
```

Shortly after, the server crashes with "Root tag must be a named compound tag" as the reason, but I don't know if this is related.
