### ISSUE TITLE
🐞 

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [LeoBeliik/ExtremeSoundMuffler#46]
### Extreme sound muffler version

3.30_fabric-1.19

### Forge / Fabric version

Fabric

### Describe the bug

[crash-2022-07-28_20.33.28-client.txt](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/9215332/crash-2022-07-28_20.33.28-client.txt)
 Whenever you go to save the settings for whatever sounds you want to muffle the game crashes with the above crash report

**Comment by LeoBeliik** [comment]
could you try deleting the ESM folder that's inside the pack folder and try to muffle a sound again?

**Comment by M0nkeyPr0grammer** [comment]
[crash-2022-07-29_10.35.25-client.txt](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/9221304/crash-2022-07-29_10.35.25-client.txt)
Deleted the folder and it still crashes with this report
