### ISSUE TITLE
🐞 Crash after saving changes

### ISSUE THREAD

**Issue by mouro001** [LeoBeliik/ExtremeSoundMuffler#48]
### Extreme sound muffler version

3.28

### Forge / Fabric version

Forge - 40.1.73

### Additional mod(s) version (If bug is due incompatibility)

Using the modpack All the Mods 7 (1.18.2)

### Describe the bug

The game crashes when closing the interface

### Steps to reproduce

1. Open the interface
2. Change the percentage of a sound
3. Press ESC to close the interface
4. Game crashes

### Additional context

[crash-2022-08-30_12.51.13-client.txt](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/9452725/crash-2022-08-30_12.51.13-client.txt) https://pastebin.com/9eSBzW2v

Using the modpack All The Mods 7, version: 0.4.29

**Comment by mouro001** [comment]
Here's the log file:
[2022-08-30-1.log](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/9452776/2022-08-30-1.log)

And the contents of `config/extremesoundmuffler-client.toml`
[extremesoundmuffler-client.toml.txt](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/9452782/extremesoundmuffler-client.toml.txt) https://pastebin.com/R4mutabP

**Comment by LeoBeliik** [comment]
~~Try deleting the ESM folder that's inside the pack folder and see if it still crashes.
Are you playing on a server?~~

nvm, I fixed this in 1.19 and forgot to  do the same in 1.18

**Comment by mouro001** [comment]
I am playing on a server yes. Will deleting the ESM folder do anything?

Are you going to release the new fixed version?

**Comment by LeoBeliik** [comment]
yes, it should be in curseforge and modrinth any time now

**Comment by mouro001** [comment]
Thank you!
