### ISSUE TITLE
Add a way to clear the sound list from the menu

### ISSUE THREAD

**Issue by pocinhas** [LeoBeliik/ExtremeSoundMuffler#49]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more of a misc feature. I'd like to suggest a way to clear the sound list (the list which shows all sound nodes) as it can get overflowed really fast.

**Describe the solution you'd like**
A button within the menu to clear the list allowing for new recent sounds to show up once again.

**Describe alternatives you've considered**
None really, I consider my button within the menu suggestion to be fitting and non intrusive.

**Comment by LeoBeliik** [comment]
There's already a way to do this, shift+click the trash button.
if you hold shift, you'll see the trash icons turns into a.. circular arrow? I think. That's the indicator

**Comment by LeoBeliik** [comment]
Yep, I wanted to be sure, it's in the Tips https://github.com/LeoBeliik/ExtremeSoundMuffler/blob/8230503927a23ba2d45f3352245cef7e15e83a8a/Common/src/main/resources/assets/extremesoundmuffler/lang/en_us.json#L56

**Comment by pocinhas** [comment]
Completely missed it, thanks for the fast reply, appreciate it. And also appreciate your work it has been much help in the making of a sound resource pack ;)
