### ISSUE TITLE
[1.15.2] Mod Interaction - Curios

### ISSUE THREAD

**Issue by TheUntamed** [LeoBeliik/ExtremeSoundMuffler#5]
Opening the Curios Inventory removes the Inventory Button.
![Screenshot_1](https://user-images.githubusercontent.com/48363903/79311287-8025ad80-7efd-11ea-8dd0-6b46cb47e6fe.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/48363903/79311292-8156da80-7efd-11ea-9f4c-b9f3b51c1e27.jpg)

I opened a issue at Curios github
https://github.com/TheIllusiveC4/Curios/issues/47#issuecomment-613846300
and they said they cannot fix it and the button has to be added to their inventory as well.

**Comment by LeoBeliik** [comment]
Is this a problem tho?
It only happens when open the Curios inventory, do people uses Curios inventory as main inventory or something?

**Comment by TheUntamed** [comment]
Yes. The key idea is to open Curios Inventory with "E" instead of the normal inventory.
Because I don't see a reason why you would want to close Curios except for the reason mentioned in this issue.
