### ISSUE TITLE
🐞 

### ISSUE THREAD

**Issue by RealMangorage** [LeoBeliik/ExtremeSoundMuffler#55]
### Extreme sound muffler version

3.35

### Forge / Fabric version

1.19.2

### Additional mod(s) version (If bug is due incompatibility)

TIAB Curio Support 1.3

### Describe the bug

It screws with my mod.

### Steps to reproduce

Load this mod with my mod (Time in a bottle Curio Support)

### Crashlog

https://pastebin.com/TwFQRrWj

**Comment by LeoBeliik** [comment]
fixed on 91932224bc0168b5b8c6883f432589de0058d584
