### ISSUE TITLE
Icon isn't showing

### ISSUE THREAD

**Issue by ClassicChad** [LeoBeliik/ExtremeSoundMuffler#58]
### Extreme sound muffler version

3.38

### Forge / Fabric version

Fabric

### Describe the bug

I updated the Sound Muffler for Fabric and now my icon has disappeared. I managed to set up a keybind for it but still no icon. Any help is greatly appreciated.

### Additional context

I last dragged the icon to be beside the recipe book and then it disappeared. (Was on Friday)

I saw there was an update for it today, so I removed the old jar file and replaced it with the current jar file. Hoping it would make the icon reappear but no luck.

**Comment by LeoBeliik** [comment]
Could you try deleting the extremesoundmuffler.json5 file in your pack's config folder?
It's probably that the problem that made the button jump all over the place had moved it out of screen, alternatively you could just set the "invButtonHorizontal" to 75 and "invButtonVertical" to 7 in the config file.

**Comment by ClassicChad** [comment]
I just edited the numbers in the config file and that fixed it. Thanks so much!
