### ISSUE TITLE
Invalid icon for Fabric Mod Menu

### ISSUE THREAD

**Issue by Giacomino99** [LeoBeliik/ExtremeSoundMuffler#59]
### Extreme sound muffler version

3.38

### Forge / Fabric version

Fabric 0.14.21 (Minecraft 1.20)

### Additional mod(s) version (If bug is due incompatibility)

[Mod Menu 7.0.1](https://modrinth.com/mod/modmenu)

### Describe the bug

When opening the Mods menu in game, an error is thrown relating to the ESM's icon and the icon is not displayed. All icons in the menu must be square and ESM's logo is not.

### Steps to reproduce

1. Go click on "Mods" button on Minecraft main menu.
2. Scroll down to the listing for "Extreme Sound Muffler."
3. There should be a default question mark icon displayed instead of the mod's actual icon.
4. View Minecraft logs to see that the error is caused by the icon not being square.

### Crashlog

https://imgur.com/cy1A7Ds

### Additional context

Changing the icon (esm_logo.png) to a square version no longer causes an error and displays correctly in game.. I have attached the file that I used to test the fix for the issue. 
![esm_logo](https://github.com/LeoBeliik/ExtremeSoundMuffler/assets/37887995/6ecbe12e-77b5-4211-9061-27338cc1fb1c)

**Comment by LeoBeliik** [comment]
Does the game crash or just outputs an error?

**Comment by Giacomino99** [comment]
It outputs an error and fails to display an icon. It does not crash the game.
