### ISSUE TITLE
[1.14.4/1.15.2] Hidden Muffler button while in Creative mode? (Overlaps with Curious Button.)

### ISSUE THREAD

**Issue by Gbergz** [LeoBeliik/ExtremeSoundMuffler#6]
Title^

Can't access the Curios Menu.

Preview with both Curios & Extreme Sound Muffler:
https://gyazo.com/d61c76b4a14310f50e7b2894aec27013

Preview with only Extreme Sound muffler:
https://gyazo.com/469dd95f1f874b309958d8a9551db201

Any ideas?
Latest version available on both mods while this issue was created.

- Gbergz

**Comment by LeoBeliik** [comment]
Yes, this problem is already fixed for the next release.
