### ISSUE TITLE
Make use of the mods menu mod (fabric) and the mods menu (forge) and cloth config

### ISSUE THREAD

**Issue by LeoBeliik** [LeoBeliik/ExtremeSoundMuffler#60]
add in game configs for the mod.

**Comment by adiChoudhary** [comment]
Hi @LeoBeliik,
can help if required, new to project but experienced in Java Development

**Comment by LeoBeliik** [comment]
Would be delightful

**Comment by LeoBeliik** [comment]
Neo implemented a config screen, and this mod now uses that.. I may or may not find something for Fabric.
Fixed in https://github.com/LeoBeliik/ExtremeSoundMuffler/commit/4c386d8373a9806209e00d63fd9f312c33ab6941
