### ISSUE TITLE
DataManager (Error executing task on Client)

### ISSUE THREAD

**Issue by segg21** [LeoBeliik/ExtremeSoundMuffler#61]
### Extreme sound muffler version

3.37

### Forge / Fabric version

43.2.14

### Additional mod(s) version (If bug is due incompatibility)

[ATM8 Mods](https://legacy.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4633481)

### Describe the bug

Recently some players from ATM8 & ATM9 modpack has had issues with this mod. Upon investigation it had appeared that the main issue was that `DataManager` uses `Gson#fromJson()` which can return null. Not sure exactly why it would return null, and haven't quite reproduced the issue. This should be null checked atleast with some fallback? 

Due to this code being a mixin from player constructor, the crash report is misleading, though log provided to exact line of the error, and code reference mentioned.

Log: https://mclo.gs/YTc5Rfl#L3104
Code Reference: [DataManager.java#L69](https://github.com/LeoBeliik/ExtremeSoundMuffler/blob/1.19.2/Common/src/main/java/com/leobeliik/extremesoundmuffler/utils/DataManager.java#L69)

In-case this may be another mod interfering, any feedback would be thankful. 
Thanks!

### Steps to reproduce
Haven't been reproduced _yet_

### Crashlog

Since this was a MIXIN, the crash report is mis-leading, though can provide if necessary.

**Comment by LeoBeliik** [comment]
I can't reproduce this so I have no idea why it happens, I'll add a null check and see if that fixes it, please let me know if this keeps happening.
