### ISSUE TITLE
Default Muted Sounds

### ISSUE THREAD

**Issue by Cyranos** [LeoBeliik/ExtremeSoundMuffler#63]
When me & my wife use this mod, she is often confused by the UI & she finds it hard to know what she is doing, though granted she is still very much getting accustomed to playing mc & games alike.

None the less I would love to be able to just set a list of sounds that are muted from the get go with out needing them to be muted manually each time you play a world

I have manually muted the sounds for her many times though it does get quite repetitive

**Comment by LeoBeliik** [comment]
you can mute all the sounds you want, then go to your pack folder (same directory where the resources folder for texture pack is) and copy the ESM folder and paste it to any other profile you want, this also copy the anchors, if you only want the general muted sounds, copy the .dat file inside the ESM folder.
