### ISSUE TITLE
chronological order option

### ISSUE THREAD

**Issue by peow** [LeoBeliik/ExtremeSoundMuffler#64]
**Is your feature request related to a problem? Please describe.**

Currently the mod in the "Recent" tab shows the sounds in alphabetical order, it would be interesting if there was an option to show them in order from newest to oldest

![image](https://github.com/LeoBeliik/ExtremeSoundMuffler/assets/105888751/848868cf-30aa-4033-b269-df6b5425e9bb)

**Describe the solution you'd like**

Option to turn the list in chronological order

**Comment by LeoBeliik** [comment]
yeah I agree, I wanted to do this for a while now but I don't remember why haven't done it yet.

**Comment by peow** [comment]
okay, do an update to fabric 1.20.1 pls

**Comment by peow** [comment]
i tested it and it works very well, thank you
