### ISSUE TITLE
ESM seems not to work with Exotic Birds (an other muffler mod also doesn't) under conditions (other mods)

### ISSUE THREAD

**Issue by xFirefalconx** [LeoBeliik/ExtremeSoundMuffler#67]
### Extreme sound muffler version

3.30

### Forge / Fabric / NeoForge version

40.2.17

### Additional mod(s) version (If bug is due incompatibility)

Exotic Birds 1.18.2-1.8.0

Modpack:
Royal Equines: Petrified Magic V[1.1b05] (latest version available)

### Describe the bug

Basically, the birds from Exotic birds keep chirping in my modpack. I tried a different mod after this one failed, but that mod also doesn't work. I assume it's because of how Exotic Birds is sending the sounds (probably) and then modified by other mods. 
I tested it with swans. You can also try to test it with Magpies, they keep chattering quite a lot. 

This is still not narrowed down enough but I plan to after I fixed/located other bugs, I just tend to forget it altogether, that's why I make a report about it now. Maybe the logs give away something, I don't know. I'll also test the other modpack versions earlier than that to see if the issue started somewhere in between, or not. 

### Steps to reproduce

For comparison
1. Add both mods
2. Launch
3. In-game spawn an exotic bird that makes a racket
4. Open inventory
5. Search swan sound
6. Try to muffle it
7. It works

Adding it to my modpack
1. Pick the modpack I mentioned above
2. Add "Extreme Sound Muffler"
3. Launch
4. In-game spawn an exotic bird that makes a racket
5. Open inventory
6. Search swan sound
7. Try to muffle it
8. It fails

### Crashlog*Latest, not crash log

https://gist.github.com/xFirefalconx/ff896c8fefdc526e3e69d322c17ad308

### Additional context

Omega Mute 1.18.2-3.1 also fails, iirc I reported that to them back then but I didn't have the idea to separately check just the two mods. There must be an optimizer/restructure mod that breaks the chain. 

Things like Modernfix, for example (no idea if Modernfix is any bad in here though)

More info TBA! I am on it please be patient. I also don't expect you to act until I found more info but maybe you can extract some from the log alone.

**Comment by LeoBeliik** [comment]
Looking at the pack, it has a new version of dynamic surroundings, the original used to break ESM so it may be the same with this, the og DS also had a way to muffle sounds.
So, try removing DS just to test if that's the problem, if it is, try to see if it still has its own way to muffle sounds.
If that's not the problem, comment and I'll reopen this issue.

**Comment by xFirefalconx** [comment]
Thank you. I can confirm that the resurrected version does the same thing. I contacted the dev now in hope of getting some info 🙈 The other mods seem fine, I'll return if that proves to be wrong, though.
