### ISSUE TITLE
Crash: No Mods

### ISSUE THREAD

**Issue by LunarDev-git** [LeoBeliik/ExtremeSoundMuffler#68]
### Extreme sound muffler version

3.41

### Forge / Fabric / NeoForge version

Forge 47.2.19

### Describe the bug

It can happen whilst in a world but also whilst loading it, Honestly I'm at my wits end since I have no idea what is causing this besides a sound engine bug

### Crashlog

https://pastebin.com/9pV12pmA

**Comment by LeoBeliik** [comment]
you say no mods but the crashlog has a really long modlist, do you have one with only ESM? if not I'll assume it's some mod incompatibility, is this your own pack?
Also may not do anything but if you're not using neoforge, try downgrading forge to 47.2.6 or 47.1.3 (forge is in a state of disarray rn and sometimes break mods)

**Comment by LunarDev-git** [comment]
Oh hecc, sorry didn't see that part that is my bad.
I am using my own pack currently yes. 

I will note this as closed for further research on my end

As for the forge, duly noted!
