### ISSUE TITLE
Button is overlapped with creative inventory page button

### ISSUE THREAD

**Issue by Phoupraw** [LeoBeliik/ExtremeSoundMuffler#69]
### Extreme sound muffler version

3.41

### Forge / Fabric / NeoForge version

Fabric Loader 0.15.6, Fabric API 0.19.0+1.20.1

### Describe the bug

![2024-02-03_08 14 27](https://github.com/LeoBeliik/ExtremeSoundMuffler/assets/50520903/dba3f3d4-2da1-4ea7-b4b6-fa7cf70ceee9)
The creative page button overlaps the sound muffler button. Clicking the page button triggers both page and sound muffler.

### Steps to reproduce

1. Install any mod that adds new creative inventory tab.
2. Check the survival inventory tab.
3. The two buttons overlap.

**Comment by LeoBeliik** [comment]
Hmm I know I fixed this at some point but I guess I didn't release that fix for 1.20.1, for now you can hold right click and drag the button to the position you want or change the button position in the config.
