### ISSUE TITLE
[1.15.2] Mod Interaction: Modded Furnace

### ISSUE THREAD

**Issue by TheUntamed** [LeoBeliik/ExtremeSoundMuffler#7]
The button is showing up in the Furnace GUI of modded Furnaces/Blast Furnaces/Smoker

![Screenshot_1](https://user-images.githubusercontent.com/48363903/79637702-d99e0e80-8181-11ea-9171-6966043c58f7.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/48363903/79637776-592bdd80-8182-11ea-9205-95e6a2a31ded.jpg)

Maybe a blacklist in the config to disable the button for specific GUIs would be neat.

**Comment by LeoBeliik** [comment]
yeah, i don't think that's a problem with the modded interfaces, i certainly made a mistake on the last update.

**Comment by TheUntamed** [comment]
Ah yes, just saw vanilla ones have it too. Pretty sure they didn't in the past :)
