### ISSUE TITLE
Riding in Minecarts not muffled

### ISSUE THREAD

**Issue by jmilthedude** [LeoBeliik/ExtremeSoundMuffler#70]
### Extreme sound muffler version

3.44

### Forge / Fabric / NeoForge version

1.20.4

### Describe the bug

The sound for minecarts while riding in them cannot be muffled. It is working for moving minecarts which I am not inside.

### Steps to reproduce

1. Ride in a minecart
2. search all sounds relating to minecart
3. muffle every one
4. Still hear the minecart.

**Comment by LeoBeliik** [comment]
I can't reproduce this, does it *only* happens with minecarts?

**Comment by jmilthedude** [comment]
Yes the only thing I have noticed not honoring the muffling is minecarts while riding in them. 

I will test in another server or single player later on. 

This is happening on a Fabric server with no mods except Discord Integration installed. My client has no other sound related mods. 

I am using an anchor in a mob farm with a radius of 32. I have zombie and skeleton sounds muffled as well which are working in that anchor. 

I have another anchor at my base where there is a hopper minecart going around collecting farm items. It is being muffled properly. 

I am thinking about the logic of entities and riding entities, and maybe it's related to when the player is riding it. It looks like you have the actual individual sounds being handled though so no matter the source, if entity.minecraft.whatever is handled it shouldn't matter what method is calling the sound to be played. 

Not sure, I'm on my phone and can't investigate but just some thoughts. 

I'll test more when I'm home and try to help pinpoint what may be going on.

**Comment by LeoBeliik** [comment]
Hmm I see, anchors can't muffle that sound for some reason.. it works with the general muffling.. weird..

**Comment by LeoBeliik** [comment]
So it seems like the riding sound it's always at 0,0,0 so the anchor will only muffled it if it's in rage of those coordinates not the *actual* coordinates of the entity... I don't think there's anything I can do about that... but I'll think about it

**Comment by LeoBeliik** [comment]
I re-read this and I'm not sure now, is your problem on the anchors or the general muffling? I can reproduce this problem with anchors, because on how it minecraft plays the riding sound `(minecraft:entity.minecart.inside)`, but it seems to work normally with the general muffling.

**Comment by jmilthedude** [comment]
Yes, sorry. The issue is present within anchors.

**Comment by LeoBeliik** [comment]
Yeah because of how minecraft does the riding cart sounds it's weird to use on anchors... I guess I could use the player coords for this case but .. why don't just muffle it generally?

**Comment by jmilthedude** [comment]
For sure. I have no problem with that and definitely understand edge cases. Mojang code can be wonderful sometimes (sarcasm). I'll go with general muffling for it. 

Just thought I'd report to give you some awareness. Such a small case does not feel like a priority if it were my mod, so definitely understandable. 

Thanks for the awesome mod tho, my dude. This sort of thing should just be built into the game to be honest :) 

You can close this if you like.
