### ISSUE TITLE
Lightning sound isn't adjustable.

### ISSUE THREAD

**Issue by hxttrick** [LeoBeliik/ExtremeSoundMuffler#71]
### Extreme sound muffler version

3.44

### Forge / Fabric / NeoForge version

Fabric

### Additional mod(s) version (If bug is due incompatibility)

Fabric api 0.96.1

### Describe the bug

entity.lightning_bolt.thunder:minecraft doesn't change its volume using the slider. 1 is the same as 90 or not muffled at all. Only when its volume is set to 0 does it go completely silent.

**Comment by LeoBeliik** [comment]
Hmm.. yes that's interesting, the thundering.. reverb?.. sound doesn't seem to respect the set volume.. I'll take a look at it and see if there's anything I can do
