### ISSUE TITLE
Item Plops from Create

### ISSUE THREAD

**Issue by RobertLSnead** [LeoBeliik/ExtremeSoundMuffler#75]
### Extreme sound muffler version

3.39

### Forge / Fabric / NeoForge version

Forge 43.3.7

### Additional mod(s) version (If bug is due incompatibility)

Mod Pack: Haven CaveBlock 1.3.2
Minecraft 1.19.2
Mod Affected: Create 

### Describe the bug

Unable to mute item plops from the create mod.

### Steps to reproduce

1. Launch Mod Pack
2. Create the Setup for any Deployer
3. Try to Mute Item Plops
4. Unable to ....

### Additional context

Only Related to Create Mod Sounds!

**Comment by LeoBeliik** [comment]
it works for me by muffling the `entity.item.pickup:minecraft`, are you muffling that?

**Comment by RobertLSnead** [comment]
That seems to work, for what ever reason I had to search for it as it was not showing up in most recent sounds.
Not sure why it wouldn't be listed in most recent, but that did work.  Anyway to have that listed in most recent to help prevent reported bugs on the issue?

**Comment by LeoBeliik** [comment]
It showed in the latest sound list for me, tho I was on a test world with no other sounds, I assume it just was in between various other sounds?
If you hold shift whilst in the resent sounds screen, the trash can button will change and pressing it will delete all the recent sounds in the list, re open the screen and you'll have less sounds.
