### ISSUE TITLE
Crush with new version and other mod (Blue Skies)

### ISSUE THREAD

**Issue by uhloin** [LeoBeliik/ExtremeSoundMuffler#79]
### Extreme sound muffler version

3.47

### Forge / Fabric / NeoForge version

NeoForge 47.1.100

### Additional mod(s) version (If bug is due incompatibility)

https://www.curseforge.com/minecraft/mc-mods/blue-skies/files/5010316
https://www.curseforge.com/minecraft/mc-mods/structure-gel-api/files/5278429

### Describe the bug

Crush on enter to portal to Blue Skies dimension

### Steps to reproduce

1. Install these mods:
https://www.curseforge.com/minecraft/mc-mods/blue-skies/files/5010316
https://www.curseforge.com/minecraft/mc-mods/structure-gel-api/files/5278429
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler/files/5486200
2. Clear config and ESM folders just for case
3. Start Minecraft 1.20.1 with forge 1.47.100
4. Create a new world in creative mode
5. Create Nether-like portal but with Turquoise Stone Bricks 
6. Activate it with Zeal Lighter
7. Enter to portal
8. Here is game crash
But there is no problems with version extremesoundmuffler-3.41-forge-1.20.jar 

[crash-2024-07-02_23.54.20-client.txt](https://github.com/user-attachments/files/16073719/crash-2024-07-02_23.54.20-client.txt)

### Crashlog

See attachment

**Comment by LeoBeliik** [comment]
fixed in https://github.com/LeoBeliik/ExtremeSoundMuffler/commit/a017726c60e7beef2a2113247315e39ce3194761

**Comment by uhloin** [comment]
Thank you, I updated mod, no more crushes
