### ISSUE TITLE
Issues with journeymap in MC 1.15

### ISSUE THREAD

**Issue by theboo** [LeoBeliik/ExtremeSoundMuffler#8]
Running latest release of extreme sound muffler and journeymap. There is an issue where panning in the journeymap full screen is very slow, does not follow the mouse speed at all. With extreme sound muffler removed, panning around the map follows the mouse speed as normal. Reporting to journeymap issue tracker as well.

Was reported in enigmatica 5 github but happens with just those two mods installed as well.

line to issue in journeymap issue tracker

https://github.com/TeamJM/journeymap/issues/211#issue-606804338

**Comment by LeoBeliik** [comment]
hey, can you test this? i have no experience with Journeymap, so I'm not sure how it works normally.
[extremeSoundMuffler-jm-test-1.15.2.zip](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/4534366/extremeSoundMuffler-jm-test-1.15.2.zip)

**Comment by theboo** [comment]
Yeh I will test it when I get home from work in a couple hours

**Comment by LeoBeliik** [comment]
Thank you

**Comment by theboo** [comment]
yup, i dont see the same issues with that test .jar. Seems good to me!
