### ISSUE TITLE
Crash on startup with NeoForge 21.0.86

### ISSUE THREAD

**Issue by NielsPilgaard** [LeoBeliik/ExtremeSoundMuffler#80]
### Extreme sound muffler version

ExtremeSoundMuffler-3.48-neoforge-1.21

### Forge / Fabric / NeoForge version

NeoForge 21.0.86

### Additional mod(s) version (If bug is due incompatibility)

Listen in the crash report

### Describe the bug

I crash on startup when I have NeoForge 21.0.86 and ExtremeSoundMuffler in the same instance.

### Crashlog

https://gist.github.com/NielsPilgaard/45f915b28642f7115a1f713f1abdce12

**Comment by LeoBeliik** [comment]
I can't reproduce this with only ESM, seems there's another mod breaking this.. is this pack available anywhere?

**Comment by NielsPilgaard** [comment]
Oh I see. It's Enigmatica 10 dev, I'll get you a modlist asap 👍

**Comment by NielsPilgaard** [comment]
Seems like the issue was caused by 3 other mods, by the looks of my latest.log: https://gist.github.com/NielsPilgaard/3d26004754b74848b52075dfdaf77e65

Sorry for the false alarm 😅
