### ISSUE TITLE
[Neoforge - 1.21] Crash on Startup

### ISSUE THREAD

**Issue by MokahTGS** [LeoBeliik/ExtremeSoundMuffler#81]
### Extreme sound muffler version

3.48

### Forge / Fabric / NeoForge version

Neoforge 21.0.112

### Additional mod(s) version (If bug is due incompatibility)

Modlist: https://pastebin.com/JuQRrjmH

### Describe the bug

Client crashes at startup

### Crashlog

https://pastebin.com/N17yUzPR

**Comment by LeoBeliik** [comment]
seems to be the same crash than #80, can you share your latest.log? incidentally, can you start the pack without ESM?
