### ISSUE TITLE
Incompatibility with Minecolonies

### ISSUE THREAD

**Issue by Thodor12** [LeoBeliik/ExtremeSoundMuffler#82]
### Extreme sound muffler version

3.48

### Forge / Fabric / NeoForge version

Forge 47.2.20

### Additional mod(s) version (If bug is due incompatibility)

- Minecolonies, version 1.20.1-1.1.629-BETA
- Dependencies of Minecolonies

### Describe the bug

In Minecolonies we have sounds for all of the citizens. We have a client side option to disable citizen voices if people want to.
This uses Forge its PlaySoundEvent to set the playing sound to null [see here](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/event/ClientEventHandler.java#L98-L114).

However with this mod enabled the config option to disable the voices seems like it has no effect, presumably due to your involvement of mixins.

Expectation is that adherence should be given if sounds are already getting disabled through another manner, and not magically re-renabling sound playing.

### Steps to reproduce

- Install a pack with Minecolonies and sound muffler
- In your `minecolonies-client.config` turn `enablecitizenvoices` to `false`
- Create a colony in your test world
- Wait for a citizen to spawn
- Interact with the citizen and you should hear them talking, expecting this not to happen

**Comment by LeoBeliik** [comment]
I can't reproduce this with only Minecolonies (and deps) and ESM, the config option works as intended.

**Comment by LeoBeliik** [comment]
did more testing and ESM doesn't even pick the voice sound when they're disabled in the config, you sure is a problem with this mod?

**Comment by Thodor12** [comment]
From what I gathered from the user reporting it on our Discord they could only get the sounds to not play when it was added to your config where it was listed to be blocked.
If it wasn't added to that config, it would play regardless, which led me to believe there's some sort of conflict

**Comment by Thodor12** [comment]
I just did a test myself and I indeed can't seem to get this to break either, the user reporting this is playing ATM9 so there's probably something else going on in that case.
Thanks for your time!
