### ISSUE TITLE
unable to load on server (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [LeoBeliik/ExtremeSoundMuffler#84]
### Extreme sound muffler version

latest

### Forge / Fabric / NeoForge version

neoforge .72

### Additional mod(s) version (If bug is due incompatibility)

nah, not needed

### Describe the bug

https://mclo.gs/gmEFB1C

### Steps to reproduce

https://mclo.gs/gmEFB1C

### Crashlog

https://mclo.gs/gmEFB1C

### Additional context

https://mclo.gs/gmEFB1C

**Comment by LeoBeliik** [comment]
ESM is clientside, it shouldn't be on the server

**Comment by VaporeonScripts** [comment]
i know, but shouldnt it skip it if its client side?
