### ISSUE TITLE
Fabric version 3.48.3 version requirement incorrect?

### ISSUE THREAD

**Issue by wapachoo** [LeoBeliik/ExtremeSoundMuffler#85]
### Extreme sound muffler version

3.48.3

### Forge / Fabric / NeoForge version

0.16.7

### Describe the bug

Update description on Modrinth claims that 3.48.3 should be compatible with both 1.21.2 and 1.21.3, but fails to launch claiming incorrect version.

### Steps to reproduce

Attempt to launch the game with ESM 3.48.3 installed on 1.21.3.

**Comment by LeoBeliik** [comment]
I can't believe I did this twice (o-_-o)
