### ISSUE TITLE
Unable to install Fabric version of this mod on 1.20.1 Prominence II: Hasturian Era

### ISSUE THREAD

**Issue by Tao-NL** [LeoBeliik/ExtremeSoundMuffler#86]
### Extreme sound muffler version

Latest Fabric

### Forge / Fabric / NeoForge version

Fabric

### Describe the bug

Mod lists correct version support in CurseForge launcher but CurseForge won't let me install mod to profile Prominence II: Hasturian Era Game version 1.20.1 fabric 0.16.5. Option greyed out.

### Steps to reproduce

Try to install mod through the launcher

**Comment by LeoBeliik** [comment]
I can add the mod on that pack fine with the ATLauncher, so I would seem that the problem comes from the curseforge launcher, which I don't think I can do anything about?
I haven't use the cf launcher in ages so I don't know why wouldn't let you install esm... are you trying to install it in the server maybe?

**Comment by Tao-NL** [comment]
Thank you for confirming it should work, I just installed in manually on my single player installation to test it.

From: https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler-fabric-official

I receive the following error while booting:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Extreme Sound Muffler' (extremesoundmuffler) 3.48.4 with any version that is compatible with:
		 - fabricloader 0.16.5
		 - minecraft 1.20.1
		 - java 17
More details:
	 - Mod 'Extreme Sound Muffler' (extremesoundmuffler) 3.48.4 requires version 0.16.7 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.16.5!
	 - Mod 'Extreme Sound Muffler' (extremesoundmuffler) 3.48.4 requires any version between 1.21.2 (inclusive) and 1.22- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Extreme Sound Muffler' (extremesoundmuffler) 3.48.4 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Tao-NL** [comment]
Oops, my bad! It is still early. I downloaded the incorrect version by mistake. I can confirm it works fine when installing manually. I guess it's just a curseforge bug when installing via launcher. May switch launchers, thanks for your time.
